### ISSUE TITLE
Username, real name usage is inconsistent

### ISSUE THREAD

**Issue by fonglh** [moexmen/hacktoberfest-leaderboard#8]
#3 suggests that username should be used when specifying the "bozz" user. However, the `avatarResult` struct actually gets the real name from github.

Since the real name can be null (see [xeluna](https://api.github.com/users/xeluna)), fallback on `login` for the display name when the name is empty.

The conditional for the "bozz" user should also be based on `login` rather than `name`.
https://github.com/moexmen/hacktoberfest-leaderboard/blob/master/main.go#L66

**Comment by naomilwx** [comment]
actually fixed in #7

**Comment by fonglh** [comment]
Yup just saw it, the real name fallback still needs to be done though. #7 fixes the 2nd part.
